#!/usr/bin/env python3
"""
requirements_manager.py — Manage all requirements.txt files across the project.

Usage:
    python requirements_manager.py                  # Show status overview
    python requirements_manager.py install          # Install all requirements
    python requirements_manager.py merge            # Merge all into one file
    python requirements_manager.py check            # Check which packages are missing
    python requirements_manager.py list             # List all unique packages
    python requirements_manager.py freeze           # Show installed vs required versions
    python requirements_manager.py outdated         # Check for outdated packages
"""

import subprocess
import sys
import re
import argparse
from pathlib import Path
from collections import defaultdict

PROJECT_ROOT = Path(__file__).resolve().parent

SKIP_DIRS = {".git", ".kilo", "old", "__pycache__", ".venv", "env", "node_modules"}


def find_requirements() -> list[Path]:
    results = []
    for p in sorted(PROJECT_ROOT.rglob("requirements.txt")):
        parts = set(p.relative_to(PROJECT_ROOT).parts)
        if parts & SKIP_DIRS:
            continue
        results.append(p)
    return results


def parse_requirements(path: Path) -> list[dict]:
    entries = []
    for line in path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("--") or stripped.startswith("-r ") or stripped.startswith("-c "):
            entries.append({"raw": stripped, "type": "flag"})
            continue
        m = re.match(r"^([A-Za-z0-9_.-]+)\s*(.*)?$", stripped)
        if m:
            entries.append({"name": m.group(1).lower(), "specifier": (m.group(2) or "").strip(), "raw": stripped, "type": "package"})
        else:
            entries.append({"raw": stripped, "type": "raw"})
    return entries


def cmd_status():
    reqs = find_requirements()
    print(f"Found {len(reqs)} requirements.txt files:\n")
    for path in reqs:
        rel = path.relative_to(PROJECT_ROOT)
        entries = parse_requirements(path)
        pkgs = [e for e in entries if e["type"] == "package"]
        flags = [e for e in entries if e["type"] == "flag"]
        print(f"  {rel}")
        print(f"    {len(pkgs)} packages, {len(flags)} pip flags")
    print()


def cmd_install():
    reqs = find_requirements()
    for path in reqs:
        rel = path.relative_to(PROJECT_ROOT)
        print(f"\nInstalling {rel} ...")
        result = subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", str(path), "--quiet"],
            cwd=str(PROJECT_ROOT),
        )
        if result.returncode == 0:
            print(f"  OK")
        else:
            print(f"  FAILED (exit code {result.returncode})")
    print("\nDone.")


def cmd_merge():
    reqs = find_requirements()
    seen = {}
    for path in reqs:
        rel = path.relative_to(PROJECT_ROOT)
        for e in parse_requirements(path):
            if e["type"] != "package":
                continue
            name = e["name"]
            spec = e["specifier"]
            if name not in seen:
                seen[name] = {"spec": spec, "sources": [str(rel)]}
            else:
                seen[name]["sources"].append(str(rel))
                if spec and not seen[name]["spec"]:
                    seen[name]["spec"] = spec

    lines = [
        "# Merged requirements from all tools",
        "# Generated by: python requirements_manager.py merge",
        "#",
    ]
    for name in sorted(seen.keys()):
        info = seen[name]
        spec = info["spec"]
        sources = ", ".join(sorted(set(info["sources"])))
        lines.append(f"{'#':<4}{name} ({sources})")
        lines.append(f"{name}{spec}" if spec else name)
    lines.append("")

    out = PROJECT_ROOT / "requirements.merged.txt"
    out.write_text("\n".join(lines))
    print(f"Wrote {len(seen)} packages to {out.relative_to(PROJECT_ROOT)}")


def cmd_list():
    reqs = find_requirements()
    by_name = defaultdict(list)
    for path in reqs:
        rel = str(path.relative_to(PROJECT_ROOT))
        for e in parse_requirements(path):
            if e["type"] == "package":
                by_name[e["name"]].append({"spec": e["specifier"], "source": rel})

    print(f"{'Package':<35} {'Spec':<20} {'Locations'}")
    print("-" * 90)
    for name in sorted(by_name.keys()):
        entries = by_name[name]
        specs = sorted(set(e["spec"] for e in entries)) or [""]
        sources = sorted(set(e["source"] for e in entries))
        print(f"{name:<35} {specs[0]:<20} {', '.join(sources)}")
        for s in specs[1:]:
            print(f"{'':<35} {s:<20}")


def cmd_check():
    reqs = find_requirements()
    missing = []
    for path in reqs:
        for e in parse_requirements(path):
            if e["type"] != "package":
                continue
            name = e["name"].replace("-", "_").replace(".", "_")
            result = subprocess.run(
                [sys.executable, "-c", f"import importlib; print(importlib.util.find_spec('{name}') and 'ok' or 'missing')"],
                capture_output=True, text=True,
            )
            status = result.stdout.strip()
            if status != "ok":
                missing.append((e["name"], str(path.relative_to(PROJECT_ROOT)), e["raw"]))
    if missing:
        print(f"Missing packages ({len(missing)}):\n")
        for name, src, raw in missing:
            print(f"  {name:<30} required by {src}")
            print(f"    install: pip install '{raw}'")
    else:
        print("All packages installed.")


def cmd_freeze():
    reqs = find_requirements()
    required = {}
    for path in reqs:
        for e in parse_requirements(path):
            if e["type"] == "package":
                required[e["name"]] = e["specifier"]

    result = subprocess.run(
        [sys.executable, "-m", "pip", "list", "--format=json"],
        capture_output=True, text=True,
    )
    import json
    installed = {p["name"].lower(): p["version"] for p in json.loads(result.stdout)}

    print(f"{'Package':<35} {'Required':<20} {'Installed'}")
    print("-" * 75)
    for name in sorted(required.keys()):
        spec = required[name] or "*"
        ver = installed.get(name, "NOT INSTALLED")
        print(f"{name:<35} {spec:<20} {ver}")


def cmd_outdated():
    result = subprocess.run(
        [sys.executable, "-m", "pip", "list", "--outdated", "--format=json"],
        capture_output=True, text=True,
    )
    import json
    try:
        packages = json.loads(result.stdout)
    except json.JSONDecodeError:
        print("Could not check outdated packages.")
        return

    if not packages:
        print("All packages are up to date.")
        return

    print(f"{'Package':<30} {'Installed':<15} {'Latest'}")
    print("-" * 60)
    for p in sorted(packages, key=lambda x: x["name"]):
        print(f"{p['name']:<30} {p['version']:<15} {p['latest_version']}")


def main():
    commands = {
        "install": ("Install all requirements", cmd_install),
        "merge": ("Merge all into requirements.merged.txt", cmd_merge),
        "check": ("Check which packages are missing", cmd_check),
        "list": ("List all unique packages across files", cmd_list),
        "freeze": ("Show installed vs required versions", cmd_freeze),
        "outdated": ("Check for outdated packages", cmd_outdated),
        "status": ("Show overview of all requirements files", cmd_status),
    }

    parser = argparse.ArgumentParser(
        description="Manage all requirements.txt files across the project",
    )
    parser.add_argument(
        "command",
        choices=list(commands.keys()),
        nargs="?",
        default="status",
        help="Command to run (default: status)",
    )
    args = parser.parse_args()

    desc, func = commands[args.command]
    print(f"# {desc}\n")
    func()


if __name__ == "__main__":
    main()
