"""Pod scraping (Phase A): env_strip inverse-of-generator + harvest --from-pod.

The --from-pod tests inject a FAKE `podman` executable on PATH that answers
the exact `podman exec <db> psql/pg_isready` invocations harvest-config.sh
makes — no real podman, no real containers.
"""

import json
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
STRIP = REPO / "deploy" / "env_strip.py"
HARVEST = REPO / "deploy" / "harvest-config.sh"

GENERATED = """\
# [bundle] GENERATED by startcluster from /x/my-bundles/b/env/.env
# [bundle] mode=work 2026-09-19T00:00:00+00:00
# [bundle] the BUNDLE is the source of truth — edit there and re-run startcluster.

MCP_UI_HOST=0.0.0.0
MCP_UI_SECRET=live-secret
BRAVE_SEARCH_API_KEY=brave-key
CUSTOM_TOOL_KEY=user-added
TURSO_DATABASE_URL=file:/home/gr/turso_data/memorymcp.db
DB_PRESET_02=postgresql://gr:pw@192.168.1.5:5432/test
# [bundle] dropped MCP_UI_PASSWORD (state plane rewritten below)

# ---- state plane (added by startcluster --config-bundle) ----
MCP_USERS_BACKEND=db
MCP_STATE_BACKEND=db
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5433
POSTGRES_USER=mcp
POSTGRES_PASSWORD=work-abc123
POSTGRES_DB=mcp
"""

EXPECTED_STRIPPED = """\
MCP_UI_HOST=0.0.0.0
MCP_UI_SECRET=live-secret
BRAVE_SEARCH_API_KEY=brave-key
CUSTOM_TOOL_KEY=user-added
TURSO_DATABASE_URL=file:/home/gr/turso_data/memorymcp.db
DB_PRESET_02=postgresql://gr:pw@192.168.1.5:5432/test
"""


def nonempty(s: str) -> list[str]:
    return [l for l in s.splitlines() if l]


def run_strip(text: str) -> list[str]:
    p = Path("/tmp/env-strip-case.env")
    p.write_text(text)
    r = subprocess.run(["python3", str(STRIP), str(p)], capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    return nonempty(r.stdout)


def test_strip_removes_only_generated_content():
    assert run_strip(GENERATED) == nonempty(EXPECTED_STRIPPED)


def test_strip_turso_embedded_dsn_and_keeps_external():
    text = "TURSO_DATABASE_URL=http://db:8080\nTURSO_DATABASE_URL2=libsql://cloud\nS3_SECRET_KEY=x\n"
    out = run_strip(text)
    assert "http://db:8080" not in out
    assert "S3_SECRET_KEY" not in out
    assert "TURSO_DATABASE_URL2=libsql://cloud" in out


def test_strip_idempotent():
    once = "\n".join(run_strip(GENERATED))
    assert run_strip(once) == run_strip(once + "\n") or once == "\n".join(run_strip(once))
    assert nonempty("\n".join(run_strip(once))) == nonempty(once)


# ---------------------------------------------------------- harvest --from-pod


POD_USERS = {"version": 1, "users": {"poduser": {"mcp_key": "pod-key", "password_hash": "h", "role": "admin"}}}
POD_DOCS = {"disabled_tools": [], "tools": {}, "version": 9}

FAKE_PODMAN = """\
#!/bin/bash
case "$1" in
  exec)
    shift
    container="$1"; shift
    if [ "$1" = "pg_isready" ]; then exit 0; fi
    sql="$*"
    case "$sql" in
      *mcp_users_store*) echo '{"version": 1, "users": {"poduser": {"mcp_key": "pod-key", "password_hash": "h", "role": "admin"}}}' ;;
      *mcp_state_docs*) echo '{"disabled_tools": [], "tools": {}, "version": 9}' ;;
    esac
    ;;
esac
"""


def test_harvest_from_pod(tmp_path):
    import os
    root = tmp_path / "repo"
    (root / "deploy").mkdir(parents=True)
    (root / "deploy" / "harvest-config.sh").write_text((REPO / "deploy" / "harvest-config.sh").read_text())
    (root / "deploy" / "env_strip.py").write_text((REPO / "deploy" / "env_strip.py").read_text())
    (root / ".env").write_text("HOST_ONLY_KEY=1\n")  # must be superseded by --env-file
    fake_bin = tmp_path / "bin"
    fake_bin.mkdir(exist_ok=True)
    (fake_bin / "podman").write_text(FAKE_PODMAN)
    (fake_bin / "podman").chmod(0o755)

    generated = tmp_path / "work.env"
    generated.write_text(GENERATED)

    bundle = tmp_path / "b"
    env = dict(os.environ, PATH=f"{fake_bin}:{os.environ['PATH']}")
    r = subprocess.run(
        ["bash", str(root / "deploy" / "harvest-config.sh"),
         "--from-pod", "mcp-work_db_1", "--env-file", str(generated), str(bundle)],
        capture_output=True, text=True, env=env,
    )
    assert r.returncode == 0, r.stderr
    # env came from the POD env, stripped of generator content
    env_text = (bundle / "env" / ".env").read_text()
    assert nonempty(env_text) == nonempty(EXPECTED_STRIPPED)
    assert "HOST_ONLY_KEY" not in env_text
    # identity came from the POD DB, not the json seeds
    users = json.loads((bundle / "identity" / "users.json").read_text())
    assert "poduser" in users["users"]
    docs = json.loads((bundle / "identity" / "tools_config.json").read_text())
    assert docs["version"] == 9
    # manifest carries the scrape provenance
    manifest = json.loads((bundle / "manifest.json").read_text())
    assert manifest["scraped"]["db_container"] == "mcp-work_db_1"


def test_harvest_from_pod_unreachable_db_falls_back(tmp_path, monkeypatch):
    import os
    root = tmp_path / "repo"
    (root / "deploy").mkdir(parents=True)
    (root / "deploy" / "harvest-config.sh").write_text((REPO / "deploy" / "harvest-config.sh").read_text())
    (root / ".env").write_text("K=1\n")
    store = root / "home" / ".config" / "supreme-mcp-tools"
    store.mkdir(parents=True)
    (store / "users.json").write_text('{"version":1,"users":{"seeduser":{"mcp_key":"k"}}}')

    failing_bin = tmp_path / "bin"
    failing_bin.mkdir(exist_ok=True)
    (failing_bin / "podman").write_text("#!/bin/bash\nexit 1\n")
    (failing_bin / "podman").chmod(0o755)

    bundle = tmp_path / "b"
    env = dict(os.environ, PATH=f"{failing_bin}:{os.environ['PATH']}", HOME=str(root / "home"))
    r = subprocess.run(
        ["bash", str(root / "deploy" / "harvest-config.sh"),
         "--from-pod", "ghost_db_1", str(bundle)],
        capture_output=True, text=True, env=env,
    )
    assert r.returncode == 0  # E13: fallback to json seeds, loud warning
    assert any("not reachable" in w for w in r.stderr.splitlines())
    users = json.loads((bundle / "identity" / "users.json").read_text())
    assert "seeduser" in users["users"]
