#!/usr/bin/env python3
"""bundle_node_env — derive a pod env file from a harvested config bundle.

Called by startcluster.sh (flag --config-bundle) and by tests via the hidden
`./startcluster bundle-node-env <bundle> <mode>` subcommand. Pure function of
its inputs: no podman, no filesystem writes — the generated env goes to stdout,
diagnostics to stderr. Design: plans/pod-config-bundle-2026-09-17.md §3.2.

usage:
  bundle_node_env.py <bundle_dir> <mode> [existing_env] [minio_pw] [keep_dataplanes]

  bundle_dir      the harvested bundle FOLDER (reads <bundle>/env/.env)
  mode            work | pg | turso | external-pg | external-turso
  existing_env    optional env file to reuse the state-plane POSTGRES_PASSWORD
                  from (keeps an already-initialized pgdata/pg volume reachable)
  minio_pw        MINIO_ROOT_PASSWORD; "" = no MinIO -> S3_* is stripped
  keep_dataplanes "1" = do NOT strip file: data-plane lines (escape hatch)

Safety property: in every test mode, lines whose value is a `file:` URL are
dropped (a file: store can never be shared across containers, and pointing the
test bench at the real memory store would let experiments write real data).
Work mode keeps file: lines — the work env mounts the host turso dir at the
same path, exactly like the host launcher.
"""

from __future__ import annotations

import os
import re
import secrets
import sys
from datetime import datetime, timezone
from typing import NoReturn

KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=(.*)$")

# keys compose sets itself via `environment:` — a bundle copy would be inert noise
COMPOSE_MANAGED = ("TOOLS_LIST", "MCP_NODE_NAME", "MCP_NODE_CENTRAL_URL", "MCP_API_URL")
STATE_KEYS = ("MCP_USERS_BACKEND", "MCP_STATE_BACKEND",
              "POSTGRES_HOST", "POSTGRES_PORT", "POSTGRES_USER",
              "POSTGRES_PASSWORD", "POSTGRES_DB")


def fail(msg: str) -> NoReturn:
    print(f"FATAL: {msg}", file=sys.stderr)
    sys.exit(1)


def note(msg: str) -> None:
    print(f"[bundle] {msg}", file=sys.stderr)


def read_pairs(path: str) -> list[tuple[str | None, str]]:
    """(key or None, raw_line) in file order. None = comment/blank/unkeyed line."""
    pairs: list[tuple[str | None, str]] = []
    for raw in open(path, encoding="utf-8"):
        line = raw.rstrip("\n")
        m = KEY_RE.match(line)
        pairs.append((m.group(1) if m else None, line))
    return pairs


def existing_password(path: str) -> str:
    try:
        for raw in open(path, encoding="utf-8"):
            m = KEY_RE.match(raw.strip())
            if m and m.group(1) == "POSTGRES_PASSWORD" and m.group(2):
                return m.group(2)
    except OSError:
        pass
    return ""


def main() -> None:
    if len(sys.argv) < 3:
        fail("usage: bundle_node_env.py <bundle_env> <mode> [existing_env] [minio_pw] [keep_dataplanes]")
    bundle_env, mode = sys.argv[1], sys.argv[2]
    existing_env = sys.argv[3] if len(sys.argv) > 3 else ""
    minio_pw = sys.argv[4] if len(sys.argv) > 4 else ""
    keep_dp = len(sys.argv) > 5 and sys.argv[5] == "1"

    if mode not in ("work", "pg", "turso", "external-pg", "external-turso"):
        fail(f"unknown mode '{mode}'")
    bundle_env = os.path.join(sys.argv[1], "env", ".env")
    try:
        pairs = read_pairs(bundle_env)
    except OSError as e:
        fail(f"cannot read bundle env: {e}")

    # dotenv last-wins: final value per key, emitted once at first occurrence
    final: dict[str, str] = {}
    for key, line in pairs:
        if key is not None:
            final[key] = KEY_RE.match(line).group(2)  # type: ignore[union-attr]

    out: list[str] = [
        f"# [bundle] GENERATED by startcluster from {bundle_env}",
        f"# [bundle] mode={mode} {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        "# [bundle] the BUNDLE is the source of truth — edit there and re-run startcluster.",
        "",
    ]

    dropped_presets: set[str] = set()
    state_block: list[str] = []

    def is_file_val(key: str) -> bool:
        return final.get(key, "").startswith("file:")

    for key, line in pairs:
        if key is None:
            if line.strip():
                # comment/blank lines from the bundle stay out — this file is self-documenting
                note(f"kept out a non-KEY=VALUE line: {line.strip()[:60]!r}")
            continue

        # --- compose-managed keys: inert (compose `environment:` wins) ---
        if key in COMPOSE_MANAGED:
            out.append(f"# [bundle] dropped {key} (set by compose for this service)")
            continue

        # --- host-only test DSN: never meaningful inside a container ---
        if key == "POSTGRES_TEST_DSN":
            out.append(f"# [bundle] dropped {key} (host-only test DSN)")
            continue

        # --- data-plane safety: file: URLs cannot cross into containers ---
        if mode != "work" and not keep_dp and is_file_val(key):
            if key.startswith("DB_PRESET_"):
                base = key.rsplit("_DESC", 1)[0]
                dropped_presets.add(base)
                out.append(f"# [bundle] dropped {key} (file: preset — not shareable into containers)")
            else:
                out.append(f"# [bundle] dropped {key} (file: URL — not shareable into containers)")
            continue
        # preset descriptor of an already-dropped preset
        if key.startswith("DB_PRESET_") and key.endswith("_DESC"):
            base = key[:-len("_DESC")]
            if base in dropped_presets:
                out.append(f"# [bundle] dropped {key} (descriptor of a dropped preset)")
                continue

        # --- state plane: rewritten per mode, never copied ---
        if key in STATE_KEYS:
            out.append(f"# [bundle] dropped {key} (state plane rewritten below)")
            continue
        if key == "TURSO_DATABASE_URL" or key == "TURSO_AUTH_TOKEN":
            if mode == "work":
                out.append(line)  # data plane — the work env mounts the host dir at the same path
                continue
            if mode == "external-turso" and key == "TURSO_DATABASE_URL":
                if is_file_val(key):
                    out.append(f"# [bundle] dropped {key} (file: URL — not shareable into containers)")
                    note("external-turso: the bundle has no network TURSO_DATABASE_URL — "
                         "identity plane only, no turso state plane")
                else:
                    out.append(line)  # network DSN passes through
                continue
            if mode == "external-pg" and key == "TURSO_AUTH_TOKEN":
                out.append(line)  # data-plane token for a network turso
                continue
            out.append(f"# [bundle] dropped {key} (state plane rewritten below)")
            continue
        # external-pg keeps the bundle's network POSTGRES_* as the state plane
        if mode == "external-pg" and key.startswith("POSTGRES_"):
            out.append(line)
            continue

        # --- S3/MinIO: re-added below when a password is known ---
        if key.startswith("S3_"):
            out.append(f"# [bundle] dropped {key} (S3 block rewritten below)")
            continue

        out.append(line)

    # ---------- state-plane block ----------
    out.append("")
    out.append("# ---- state plane (added by startcluster --config-bundle) ----")
    out.append("MCP_USERS_BACKEND=db")
    out.append("MCP_STATE_BACKEND=db")
    if mode == "work":
        pw = existing_password(existing_env) if existing_env else ""
        if not pw:
            pw = "work-" + secrets.token_urlsafe(16)
        state_block += ["POSTGRES_HOST=127.0.0.1", "POSTGRES_PORT=5433",
                        "POSTGRES_USER=mcp", f"POSTGRES_PASSWORD={pw}", "POSTGRES_DB=mcp"]
    elif mode == "pg":
        pw = existing_password(existing_env) if existing_env else ""
        if not pw:
            pw = "cluster-" + secrets.token_urlsafe(16)
        state_block += ["POSTGRES_HOST=db", "POSTGRES_PORT=5432",
                        "POSTGRES_USER=mcp", f"POSTGRES_PASSWORD={pw}", "POSTGRES_DB=mcp"]
    elif mode == "turso":
        state_block += ["TURSO_DATABASE_URL=http://db:8080"]
        if final.get("TURSO_AUTH_TOKEN"):
            note("dropped TURSO_AUTH_TOKEN — the embedded sqld runs open inside the compose network")
    elif mode == "external-pg":
        state_block += ["# [bundle] POSTGRES_* passed through from the bundle (external state plane)"]
    else:  # external-turso
        if final.get("TURSO_DATABASE_URL") and not final["TURSO_DATABASE_URL"].startswith("file:"):
            state_block += ["# [bundle] TURSO_DATABASE_URL passed through from the bundle (external state plane)"]
        else:
            state_block += ["# [bundle] NO state-plane DSN — fill one in (external topology) or re-harvest"]
            note("no usable state-plane DSN for external-turso")
    out += state_block

    # ---------- S3/MinIO block ----------
    if mode != "work":
        out.append("")
        if minio_pw:
            out += ["# ---- shared S3 artifacts (test cluster MinIO) ----",
                    "S3_ENDPOINT=http://minio:9000",
                    "S3_ACCESS_KEY=mcp-artifacts",
                    f"S3_SECRET_KEY={minio_pw}"]
        else:
            out.append("# [bundle] no MINIO_ROOT_PASSWORD known — no S3 artifacts plane on this node")

    print("\n".join(out))


if __name__ == "__main__":
    main()
