#!/usr/bin/env bash
# startcluster — manage the two podman environments of the project.
#
#  ENV: work  — the pod-based DAILY DRIVER (replaces startlauncher):
#       one node, all six tools, CANONICAL ports (8000-8005 + central 8200),
#       host networking, own pgvector state plane (own volume).
#       First boot imports the HOST users.json: same accounts, same keys.
#       Data planes come from the host .env (real memories, real presets).
#
#  ENV: test  — the M4 TESTING ground (two light nodes on 18xxx/19xxx,
#       shared identity plane). Never touched by your working clients.
#
#  The two environments are fully isolated: separate containers, volumes
#  and env files. Only one of {work cluster, host startlauncher} may run
#  at a time (same canonical ports). Automated tests target the canonical
#  ports: stop the work cluster first, or the suite tests the work env.
#
#  usage:
#    startcluster work [up|stop|start|status|clean|logs [svc]] [-b|--config-bundle <path>]
#    startcluster test [pg|turso|external-pg|external-turso|stop|start|status|clean|logs [svc]] [-b|--config-bundle <path>]
set -euo pipefail
ORIG_PWD="$PWD"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.."                 # repo root (compose calls do `cd deploy` from here)
REPO_ROOT="$PWD"

TEST_PROJECT="mcp-multihost"
WORK_PROJECT="mcp-work"
CONFIG_DIR="${HOME}/.config/supreme-mcp-tools"

# ---------- shared helpers ----------
usage() { sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'; cat <<'HELP'

  usage: startcluster work [up|stop|start|status|backup|restore <file>|clean|logs [svc]] [-b|--config-bundle <path>]
         startcluster test [pg|turso|external-pg|external-turso|status|stop|start|clean|logs [svc]] [-b|--config-bundle <path>]
         startcluster harvest [--zip|--redact|--from-work-db|--list] [BUNDLE_PATH]

  work:  daily-driver pod (canonical ports 8000-8005/8200; UI: startcluster work ui)
  test:  M4 two-node bench (node centrals 18200/19200)
  backup/restore: pg_dump of the work state plane <-> ~/supreme-mcp-tools-backups/

  -b <path> | --config-bundle <path|host>  seed the environment from a harvested
      config bundle (made by: startcluster harvest). 'host' (the default) keeps
      today's behavior: derive from the live host files. In test mode, file:
      data-plane lines are stripped for safety (--keep-dataplanes overrides).
  bundle-node-env <bundle> <work|pg|turso|external-pg|external-turso>
      print the env file a bundle would generate (debug/tests, no podman).
  harvest [BUNDLE_PATH]  harvest into BUNDLE_PATH; a bare NAME goes to
      <cwd>/my-bundles/<NAME>; default: <cwd>/my-bundles/bundle-<UTC ts>
HELP
}
wait_http() { # url, tries
  for _ in $(seq 1 "${2:-40}"); do curl -sf "$1" >/dev/null 2>&1 && return 0; sleep 3; done
  return 1
}

# ---------- config-bundle support (plans/pod-config-bundle-2026-09-17.md) ----------
BUNDLE_RAW="host"   # --config-bundle value, extracted from the args in the dispatch
BUNDLE_DIR=""       # resolved ABSOLUTE bundle folder; "" = host mode (today's behavior)
KEEP_DATAPLANES=0

resolve_bundle() { # $BUNDLE_RAW -> $BUNDLE_DIR ("" = host mode)
  [ "$BUNDLE_RAW" = "host" ] && return 0
  case "$BUNDLE_RAW" in
    /*) p="$BUNDLE_RAW" ;;
    *)  p="$ORIG_PWD/$BUNDLE_RAW" ;;
  esac
  if [ -f "$p" ] && [ "${p##*.}" = "zip" ]; then
    tmp="$REPO_ROOT/deploy/.bundle-tmp/$(basename "$p" .zip)"
    rm -rf "$tmp"; mkdir -p "$tmp"
    python3 -m zipfile -e "$p" "$tmp" || { echo "FATAL: cannot extract $p"; exit 1; }
    # tolerate zips that carry the bundle folder as a top-level prefix
    if [ -f "$tmp/env/.env" ]; then BUNDLE_DIR="$tmp"
    elif [ -f "$tmp/$(basename "$p" .zip)/env/.env" ]; then BUNDLE_DIR="$tmp/$(basename "$p" .zip)"
    else echo "FATAL: $p contains no env/.env — not a config bundle"; exit 1; fi
  elif [ -d "$p" ]; then
    [ -f "$p/env/.env" ] || { echo "FATAL: $p is not a config bundle (missing env/.env)"; exit 1; }
    BUNDLE_DIR="$(cd "$p" && pwd)"
  else
    echo "FATAL: bundle not found: $p"; exit 1
  fi
  echo "[bundle] using $BUNDLE_DIR" >&2
}

bundle_node_env() { # bundle_dir, mode, existing_env, minio_pw, keep_dp — env to stdout
  python3 "$REPO_ROOT/deploy/bundle_node_env.py" "$1" "$2" "${3:-}" "${4:-}" "${5:-0}"
}

minio_password() { # test-helper override via env, else deploy/.env
  if [ -n "${BUNDLE_MINIO_PW+x}" ]; then printf '%s' "$BUNDLE_MINIO_PW"; return; fi
  [ -f deploy/.env ] && sed -n 's/^MINIO_ROOT_PASSWORD=//p' deploy/.env | head -1 || true
}

write_bundle_compose() { # outfile, then service|hostpath|containerpath[:ro|rw] specs
  out="$1"; shift
  python3 - "$out" "$@" <<'PY'
import sys
out, specs = sys.argv[1], sys.argv[2:]
services: dict[str, list[str]] = {}
for s in specs:
    svc, host, cont, *rest = s.split("|")
    mode = "" if (rest or ["ro"])[0] == "rw" else ":ro"
    services.setdefault(svc, []).append(f"      - {host}:{cont}{mode}")
lines = ["# [bundle] GENERATED by startcluster --config-bundle — do not hand-edit.",
         "# Mounts the bundle's config over the image's baked copies (tweaks need no rebuild).",
         "services: {}" if not services else "services:"]
for svc in sorted(services):
    lines += [f"  {svc}:", "    volumes:"]
    lines += services[svc]
open(out, "w").write("\n".join(lines) + "\n")
PY
}

# ---------- WORK environment ----------
work_env() { action="${1:-up}"; shift || true
  PROJECT="$WORK_PROJECT"
  if [ "$action" = backup ]; then
    ts=$(date +%Y%m%d-%H%M%S)
    out="${HOME}/supreme-mcp-tools-backups/work-pg-$ts.sql"
    mkdir -p "$(dirname "$out")"
    podman exec "${PROJECT}_db_1" pg_dump -U mcp -d mcp > "$out" \
      && echo "[work] backup -> $out ($(wc -c < "$out") bytes)" \
      || { echo "[work] backup FAILED — is the work env running?"; exit 1; }
    exit 0
  fi
  if [ "$action" = restore ]; then
    f="${1:-}"   # post-shift: the file is the first remaining arg
    [ -f "$f" ] || { echo "usage: $0 work restore <backup.sql>"; exit 1; }
    echo "[work] RESTORE wipes the current work data volume (users/masks) and imports $f — type 'wipe' to confirm:"
    read -r ans; [ "$ans" = "wipe" ] || { echo "aborted"; exit 1; }
    ( cd deploy && podman-compose -p "$PROJECT" down ) 2>/dev/null || true
    podman pod rm -f "pod_$PROJECT" >/dev/null 2>&1 || true
    podman volume rm -f "${PROJECT}_work_pgdata" 2>/dev/null || true
    ( cd deploy && podman-compose -p "$PROJECT" -f compose-work.run.yml up -d db ) \
      || ( cd deploy && podman-compose -p "$PROJECT" up -d db )
    sleep 8
    podman exec -i "${PROJECT}_db_1" psql -U mcp -d mcp < "$f" >/dev/null \
      && echo "[work] restore imported — starting the node..." \
      || { echo "[work] restore import FAILED"; exit 1; }
    ( cd deploy && podman-compose -p "$PROJECT" -f compose-work.run.yml up -d work ) \
      || ( cd deploy && podman-compose -p "$PROJECT" up -d work )
    if wait_http http://127.0.0.1:8200/health 50; then
      echo "[work] restored and healthy"
    else
      echo "[work] node not healthy yet — check podman logs ${PROJECT}_work_1"; exit 1
    fi
    exit 0
  fi
  # `clean` is handled by the case below: it WIPES containers AND the state
  # volume after an explicit 'wipe' confirmation.

  # bundle mode: work.env is REGENERATED from the bundle on every up (the bundle
  # is the source of truth — edit the bundle, re-run `startcluster work`).
  # host mode keeps the one-shot bootstrap below.
  if [ -n "$BUNDLE_DIR" ]; then
    OLD_PW=""
    [ -f deploy/work.env ] && OLD_PW=$(sed -n 's/^POSTGRES_PASSWORD=//p' deploy/work.env | head -1)
    [ -f deploy/work.env ] && cp -p deploy/work.env "deploy/work.env.bak-$(date +%Y%m%d-%H%M%S)"
    bundle_node_env "$BUNDLE_DIR" work "$OLD_PW" "" 0 > deploy/work.env
    echo "[work] work.env regenerated from the bundle (previous copy backed up)"
  elif [ ! -f deploy/work.env ]; then
    [ -f .env ] || { echo "[work] FATAL: no host .env to derive work.env from"; exit 1; }
    cp .env deploy/work.env
    {
      echo ""
      echo "# ---- state plane overrides (added by startcluster work) ----"
      echo "MCP_USERS_BACKEND=db"
      echo "MCP_STATE_BACKEND=db"
      echo "POSTGRES_HOST=127.0.0.1"
      echo "POSTGRES_PORT=5433"
      echo "POSTGRES_USER=mcp"
      # Generated ONCE on first boot; rotation = edit deploy/work.env, then
      # `startcluster work clean` (wipes state) + `up` to re-bootstrap.
      echo "POSTGRES_PASSWORD=work-$(python3 -c 'import secrets; print(secrets.token_urlsafe(16))')"
      echo "POSTGRES_DB=mcp"
    } >> deploy/work.env
    echo "[work] deploy/work.env created from the host .env (data planes identical; state plane -> own pgvector)"
  fi

  # concrete compose (host paths inlined — no interpolation dependency)
  # POSIX sed (no GNU grep -oP — busybox/BSD-safe); falls back to /nonexistent
  # bundle mode: the freshly generated work.env carries the bundle's data-plane paths
  TURSO_SRC="$([ -n "$BUNDLE_DIR" ] && echo deploy/work.env || echo .env)"
  HOST_TURSO_DIR=$(sed -n 's/^TURSO_DATABASE_URL=file:\([^ ]*\).*/\1/p' "$TURSO_SRC" | xargs dirname 2>/dev/null || true)
  if [ -n "$BUNDLE_DIR" ]; then
    [ -f "$BUNDLE_DIR/identity/users.json" ] \
      || { echo "[work] FATAL: bundle missing identity/users.json (the daily driver needs its users)"; exit 1; }
    export HOST_CONFIG_DIR="$BUNDLE_DIR/identity"
  else
    export HOST_CONFIG_DIR="$CONFIG_DIR"
  fi
  export HOST_TURSO_DIR="${HOST_TURSO_DIR:-/nonexistent}"
  export HOST_HF_CACHE="${HOME}/.cache/huggingface"
  sed -e "s|\${HOST_CONFIG_DIR}|$HOST_CONFIG_DIR|g" \
      -e "s|\${HOST_TURSO_DIR}|$HOST_TURSO_DIR|g" \
      -e "s|\${HOST_HF_CACHE}|$HOST_HF_CACHE|g" \
      deploy/compose-work.yml > deploy/compose-work.run.yml

  # bundle mode: mounts the bundle's config over the image's baked copies
  # (override file comes LAST in the -f chain — podman-compose unions volumes
  # and lets later same-target mounts win; probe-verified 1.3.0 rec_merge_one)
  BUNDLE_F=()
  if [ -n "$BUNDLE_DIR" ]; then
    specs=()
    for f in "$BUNDLE_DIR"/config/*.json; do specs+=("work|$f|/app/config/$(basename "$f")|ro"); done
    for f in "$BUNDLE_DIR"/tools/*/config.json; do
      specs+=("work|$f|/app/tools/$(basename "$(dirname "$f")")/config.json|ro")
    done
    write_bundle_compose deploy/compose-work.bundle.yml ${specs[@]+"${specs[@]}"}
    BUNDLE_F=(-f compose-work.bundle.yml)
  fi

  case "$action" in
    stop)  ( cd deploy && podman-compose -p "$PROJECT" stop ) ; exit 0 ;;
    start) ( cd deploy && podman-compose -p "$PROJECT" start ) ; sleep 5 ;;
    clean)
      echo "[work] this removes containers AND the state volume (users/masks) — type 'wipe' to confirm:"
      read -r ans; [ "$ans" = "wipe" ] || { echo "aborted"; exit 1; }
      ( cd deploy && podman-compose -p "$PROJECT" down -v ) 2>/dev/null || true
      podman pod rm -f "pod_$PROJECT" >/dev/null 2>&1 || true
      echo "[work] fully wiped"; exit 0 ;;
    logs)  podman logs --tail "${3:-40}" "${PROJECT}_${2:-work}_1"; exit 0 ;;
    status)
      ( cd deploy && podman-compose -p "$PROJECT" ps ) || true
      printf "central: "; curl -sf http://127.0.0.1:8200/health || echo "not answering"
      echo; exit 0 ;;
  esac

  # default action: up (rebuild) — stop the running work env first
  echo "[work] stopping the running work env (volumes kept)..."
  ( cd deploy && podman-compose -p "$PROJECT" down ) 2>/dev/null || true
  podman pod rm -f "pod_$PROJECT" >/dev/null 2>&1 || true
  echo "[work] preflight: canonical ports must be free (host launcher down?)..."
  BUSY=$(ss -ltn | grep -cE ":(8000|8001|8002|8003|8004|8005|8200)\b" || true)
  if [ "${BUSY:-0}" -ne 0 ]; then
    echo "[work] FATAL: canonical ports busy — stop the host launcher (startlauncher) first."; exit 1
  fi

  echo "[work] grabbing latest code..."
  git pull --ff-only || echo "[work] WARNING: pull failed — deploying local code"

  echo "[work] (re)building node image + starting work env..."
  # compose reuses the tagged image if present — drop it so the build runs
  podman rmi -f localhost/mcp-node:latest localhost/mcp-work_work:latest \
              localhost/mcp-work-work_work:latest >/dev/null 2>&1 || true
  ( cd deploy && podman-compose -p "$PROJECT" -f compose-work.run.yml \
      ${BUNDLE_F[@]+"${BUNDLE_F[@]}"} up -d db work )

  echo "[work] waiting for the node central on :8200..."
  if ! wait_http http://127.0.0.1:8200/health 50; then
    echo "[work] node not healthy — check: podman logs ${PROJECT}_work_1"; exit 1
  fi

  # one-time masks/inventory adoption (users.json is auto-imported by the store)
  podman exec "${PROJECT}_work_1" python3 -c "
import sys, json
sys.path.insert(0, '/app'); sys.path.insert(0, '/app/tools')
from tools.shared import state_docs
if state_docs.load_doc(state_docs.DOC_TOOLS_CONFIG) is None:
    src = json.load(open('/root/.config/supreme-mcp-tools/tools_config.json'))
    state_docs.save_doc(state_docs.DOC_TOOLS_CONFIG, src)
    print('[work] masks+inventory imported from the host tools_config.json')
else:
    print('[work] state docs already present')
" 2>/dev/null || echo "[work] (mask seeding skipped — run again later if needed)"

  echo "[work] UP — canonical surface:"
  curl -s http://127.0.0.1:8200/health; echo
  echo "  tools: 8000-8005 | central: 8200 | UI (opt.): startcluster work ui -> 8400"
}

# ---------- TEST environment ----------
test_env() { action="${1:-pg}"; shift || true
  PROJECT="$TEST_PROJECT"
  case "$action" in
    stop)  ( cd deploy && podman-compose -p "$PROJECT" stop ) ; exit 0 ;;
    start) ( cd deploy && podman-compose -p "$PROJECT" start ) ; sleep 5 ; exit 0 ;;
    clean)
      ( cd deploy && podman-compose -p "$PROJECT" down ) 2>/dev/null || true
      podman pod rm -f "pod_$PROJECT" >/dev/null 2>&1 || true
      podman rm -f "${PROJECT}_node1_1" "${PROJECT}_node2_1" "${PROJECT}_db_1" 2>/dev/null || true
      echo "[test] removed (volumes pgdata/sqldata kept)"; exit 0 ;;
    logs)  podman logs --tail "${3:-40}" "${PROJECT}_${2:-node1}_1"; exit 0 ;;
    status)
      podman pod ls | grep "$PROJECT" || echo "[test] not created"
      printf "node1: "; curl -sf http://127.0.0.1:18200/health || echo "down"
      echo; printf "node2: "; curl -sf http://127.0.0.1:19200/health || echo "down"
      echo; exit 0 ;;
  esac
  TOPOLOGY="$action"
  case "$TOPOLOGY" in
    pg)          TOPO_FILE="compose-pg.yml";     WITH_DB=1 ;;
    turso)       TOPO_FILE="compose-turso.yml";  WITH_DB=1 ;;
    external-pg) TOPO_FILE="";                   WITH_DB=0 ;;
    external-turso) TOPO_FILE="";                WITH_DB=0 ;;
    *) echo "unknown test topology '$TOPOLOGY'"; exit 1 ;;
  esac

  # bundle mode: node.env is GENERATED from the bundle per topology (identity
  # plane copied, state plane rewritten, file: data-plane lines stripped unless
  # --keep-dataplanes). users.json mounts into node1 ONLY: its one-time import
  # seeds the shared DB; node2 reads the same DB (no concurrent-import race).
  if [ -n "$BUNDLE_DIR" ]; then
    OLD_PW=""
    [ -f deploy/node.env ] && OLD_PW=$(sed -n 's/^POSTGRES_PASSWORD=//p' deploy/node.env | head -1)
    [ -f deploy/node.env ] && cp -p deploy/node.env "deploy/node.env.bak-$(date +%Y%m%d-%H%M%S)"
    bundle_node_env "$BUNDLE_DIR" "$TOPOLOGY" "$OLD_PW" "$(minio_password)" "$KEEP_DATAPLANES" > deploy/node.env
    echo "[test] node.env generated from the bundle (previous copy backed up)"
    specs=()
    [ -f "$BUNDLE_DIR/identity/users.json" ] \
      && specs+=("node1|$BUNDLE_DIR/identity/users.json|/root/.config/supreme-mcp-tools/users.json|ro")
    [ -f "$BUNDLE_DIR/identity/tools_config.json" ] \
      && specs+=("node1|$BUNDLE_DIR/identity/tools_config.json|/root/.config/supreme-mcp-tools/tools_config.json|ro")
    for f in "$BUNDLE_DIR"/config/*.json; do
      specs+=("node1|$f|/app/config/$(basename "$f")|ro" "node2|$f|/app/config/$(basename "$f")|ro")
    done
    for f in "$BUNDLE_DIR"/tools/*/config.json; do
      t="$(basename "$(dirname "$f")")"
      specs+=("node1|$f|/app/tools/$t/config.json|ro" "node2|$f|/app/tools/$t/config.json|ro")
    done
    write_bundle_compose deploy/compose-test.bundle.yml ${specs[@]+"${specs[@]}"}
    [ -f "$BUNDLE_DIR/identity/users.json" ] || \
      echo "[test] WARNING: bundle has no identity/users.json — cluster starts without users (break-glass central key only)"
  fi

  echo "[test:$TOPOLOGY] grabbing latest code..."
  git pull --ff-only || true
  cleanup_cluster() {
    ( cd deploy && podman-compose -p "$PROJECT" down ) 2>/dev/null || true
    podman pod rm -f "pod_$PROJECT" >/dev/null 2>&1 || true
    podman rm -f ${PROJECT}_node1_1 ${PROJECT}_node2_1 ${PROJECT}_db_1 2>/dev/null || true
  }
  echo "[test] tearing down old cluster (volumes kept)..."
  cleanup_cluster
  cd deploy
  podman rmi -f localhost/${PROJECT}_node1:latest localhost/${PROJECT}_node2:latest 2>/dev/null || true
  echo "[test] starting..."
  # MinIO credentials live in deploy/.env (gitignored) — compose reads the
  # same file for ${MINIO_ROOT_PASSWORD} interpolation in compose-artifacts.yml.
  BUNDLE_F=()
  [ -n "$BUNDLE_DIR" ] && BUNDLE_F=(-f compose-test.bundle.yml)
  if [ "$WITH_DB" = 1 ]; then
    if [ ! -f deploy/.env ] || ! grep -q '^MINIO_ROOT_PASSWORD=..' deploy/.env; then
      echo "[test] FATAL: deploy/.env missing or MINIO_ROOT_PASSWORD unset —"
      echo "       add 'MINIO_ROOT_PASSWORD=<generate-one>' to deploy/.env (see deploy/README.md)"
      exit 1
    fi
    . ./deploy/.env
    podman-compose -p "$PROJECT" -f compose-common.yml -f "$TOPO_FILE" \
      -f compose-lb.yml -f compose-artifacts.yml ${BUNDLE_F[@]+"${BUNDLE_F[@]}"} up -d db node1 node2 lb minio
  else
    # external-* topologies: no embedded state plane AND no shared artifacts
    podman-compose -p "$PROJECT" -f compose-common.yml \
      -f compose-lb.yml ${BUNDLE_F[@]+"${BUNDLE_F[@]}"} up -d node1 node2 lb
  fi
  ok=0; wait_http http://127.0.0.1:18200/health 40 && ok=1
  [ "$ok" = 1 ] && echo "[test] UP: node1 :18200, node2 :19200, LB :18080 ($TOPOLOGY)" \
                || { echo "[test] nodes not healthy — podman logs ${PROJECT}_node1_1"; exit 1; }

  # bundle mode: seed masks+inventory into the shared state docs (same adoption
  # the work env does; the mounted file is only the one-time import source)
  if [ -n "$BUNDLE_DIR" ] && [ -f "$BUNDLE_DIR/identity/tools_config.json" ]; then
    podman exec "${PROJECT}_node1_1" python3 -c "
import sys, json
sys.path.insert(0, '/app'); sys.path.insert(0, '/app/tools')
from tools.shared import state_docs
if state_docs.load_doc(state_docs.DOC_TOOLS_CONFIG) is None:
    src = json.load(open('/root/.config/supreme-mcp-tools/tools_config.json'))
    state_docs.save_doc(state_docs.DOC_TOOLS_CONFIG, src)
    print('[test] masks+inventory imported from the bundle')
else:
    print('[test] state docs already present')
" 2>/dev/null || echo "[test] (mask seeding skipped — nodes read the shared state doc at next boot)"
  fi

  # MinIO artifacts bucket (credentials from deploy/.env — NOT hardcoded).
  # MC_HOST_* env form avoids -p on the command line; stat-or-create is one
  # idempotent shot (no unreliable `mc ls`-to-detect-absence dance).
  if [ "$WITH_DB" = 1 ]; then
    wait_http http://127.0.0.1:19000/minio/health/live 10 \
      || echo "[test] WARNING: MinIO health endpoint not answering yet"
    podman exec -e MC_HOST_local="http://mcp-artifacts:${MINIO_ROOT_PASSWORD}@127.0.0.1:9000" \
      ${PROJECT}_minio_1 sh -c 'mc stat local/memory-artifacts >/dev/null 2>&1 || mc mb local/memory-artifacts' \
      && echo "[test] MinIO bucket 'memory-artifacts' ready" \
      || echo "[test] WARNING: MinIO bucket bootstrap failed — check MINIO_ROOT_PASSWORD in deploy/.env"
  fi
}

# ---------- dispatch ----------
# --config-bundle / --keep-dataplanes may appear anywhere; everything else is positional
positional=()
while [ $# -gt 0 ]; do
  case "$1" in
    --config-bundle)
      [ $# -ge 2 ] || { echo "FATAL: --config-bundle needs a bundle path (or 'host')"; exit 1; }
      BUNDLE_RAW="$2"; shift 2 ;;
    --config-bundle=*) BUNDLE_RAW="${1#*=}"; shift ;;
    -b)
      [ $# -ge 2 ] || { echo "FATAL: -b needs a bundle path (or 'host')"; exit 1; }
      BUNDLE_RAW="$2"; shift 2 ;;
    --keep-dataplanes) KEEP_DATAPLANES=1; shift ;;
    *) positional+=("$1"); shift ;;
  esac
done
set -- ${positional[@]+"${positional[@]}"}

case "${1:-}" in
  "")    usage; exit 0 ;;
  work)  shift; resolve_bundle; work_env "$@" ;;
  test)  shift; resolve_bundle; test_env "$@" ;;
  pg|turso|external-pg|external-turso) resolve_bundle; test_env "$@" ;;   # legacy shorthand = test
  harvest) shift; HARVEST_INVOCATION_PWD="$ORIG_PWD" exec "$REPO_ROOT/deploy/harvest-config.sh" "$@" ;;
  bundle-node-env)   # hidden: print the env a bundle generates (tests/debug, no podman)
    shift
    # the bundle may come as a positional OR via -b/--config-bundle
    case "${1:-}" in
      "")
        echo "usage: startcluster bundle-node-env [<bundle>|(-b <bundle>)] <work|pg|turso|external-pg|external-turso> [existing_env_file]"; exit 1 ;;
      work|pg|turso|external-pg|external-turso)
        [ "$BUNDLE_RAW" != "host" ] || { echo "FATAL: no bundle given — pass <bundle> or -b/--config-bundle <path>"; exit 1; }
        MODE="$1"; EXISTING="${2:-}" ;;
      *)
        BUNDLE_RAW="$1"; MODE="${2:-}"; EXISTING="${3:-}"
        [ -n "$MODE" ] || { echo "FATAL: bundle-node-env needs a mode (work|pg|turso|external-pg|external-turso)"; exit 1; } ;;
    esac
    resolve_bundle
    bundle_node_env "$BUNDLE_DIR" "$MODE" "$EXISTING" "$(minio_password)" "$KEEP_DATAPLANES"
    exit 0 ;;
  bundle-compose)    # hidden: write a bundle override compose file (tests/debug)
    shift
    [ $# -ge 1 ] || { echo "usage: startcluster bundle-compose <outfile> [svc|host|cont[:ro|rw]]..."; exit 1; }
    out="$1"; shift
    write_bundle_compose "$out" "$@"
    exit 0 ;;
  *)     usage; echo; echo "unknown command '$1'"; exit 1 ;;
esac
